import test from 'node:test';import assert from 'node:assert/strict';import {createCollectionSync,relativeSyncTime} from '../src/services/collectionSync.js';
const donation=(id,quantity=1)=>({id,quantity,recipient:'rose',heartType:'pink'});
const tick=()=>new Promise(r=>setImmediate(r));
function harness(){let data=[donation('a',500)],time=10000,fail=false,calls=0,hold=null;const updates=[],states=[];const sync=createCollectionSync({now:()=>time,fetchData:async()=>{calls++;if(hold)await hold;if(fail)throw Error('internal secret');return data;},onData:(d,meta)=>updates.push({d,meta}),onState:s=>states.push(s)});return {sync,updates,states,setData:v=>data=v,setTime:v=>time=v,setFail:v=>fail=v,setHold:v=>hold=v,calls:()=>calls};}
test('initial, manual catchup and reconnect synchronize silently; genuine live approvals animate once',async()=>{const h=harness();await h.sync.refresh('initial');assert.equal(h.updates[0].meta.liveDonations.length,0);assert.equal(h.states.at(-1).lastSyncedAt,10000);h.setData([donation('a',500),donation('historical',5)]);h.setTime(20000);await h.sync.refresh('manual');assert.equal(h.updates.at(-1).d.reduce((n,d)=>n+d.quantity,0),505);assert.deepEqual(h.updates.at(-1).meta.liveDonations,[]);h.setData([donation('a',500),donation('historical',5),donation('live')]);h.setTime(21000);await h.sync.live('live');assert.deepEqual(h.updates.at(-1).meta.liveDonations.map(d=>d.id),['live']);assert.equal(h.states.at(-1).lastSyncedAt,21000);const n=h.calls();await h.sync.live('live');assert.equal(h.calls(),n);await h.sync.refresh('catchup');assert.deepEqual(h.updates.at(-1).meta.liveDonations,[]);});
test('manual lock and cooldown prevent duplicate requests and failure preserves last data and timestamp',async()=>{const h=harness();await h.sync.refresh('initial');let release;h.setHold(new Promise(r=>release=r));const request=h.sync.refresh('manual');assert.equal(await h.sync.refresh('manual'),false);release();await request;h.setHold(null);assert.equal(await h.sync.refresh('manual'),false);h.setTime(15000);h.setFail(true);assert.equal(await h.sync.refresh('manual'),false);assert.equal(h.updates.length,2);assert.equal(h.states.at(-1).lastSyncedAt,10000);assert.equal(h.states.at(-1).initialError,'');assert.ok(!h.states.at(-1).syncError.includes('secret'));assert.equal(h.states.at(-1).isRefreshing,false);});
test('live approvals arriving during a manual request are reconciled separately without replaying historical records',async()=>{const h=harness();await h.sync.refresh('initial');let release;h.setHold(new Promise(r=>release=r));h.setData([donation('a',500),donation('history',3),donation('new')]);const request=h.sync.refresh('manual');h.sync.live('new');release();await request;h.setHold(null);await tick();assert.deepEqual(h.updates[1].meta.liveDonations,[]);assert.deepEqual(h.updates[2].meta.liveDonations.map(d=>d.id),['new']);});
test('failed live fetch retries silently on manual refresh and old events do not reanimate',async()=>{const h=harness();await h.sync.refresh('initial');h.setFail(true);await h.sync.live('new');h.setFail(false);h.setData([donation('a'),donation('new')]);await h.sync.refresh('manual');assert.deepEqual(h.updates.at(-1).meta.liveDonations,[]);const n=h.calls();await h.sync.live('new');assert.equal(h.calls(),n);h.setData([donation('a'),donation('new'),donation('later')]);await h.sync.live('later');assert.deepEqual(h.updates.at(-1).meta.liveDonations.map(d=>d.id),['later']);});
test('disposed requests do not publish and malformed data never replaces valid collection',async()=>{const h=harness();await h.sync.refresh('initial');h.setData([{id:'bad',recipient:'other',quantity:2,heartType:'pink'}]);assert.equal(await h.sync.refresh('manual'),false);assert.equal(h.updates.length,1);h.sync.dispose();assert.equal(await h.sync.refresh('manual'),false);});
test('relative labels use local time only',()=>{assert.equal(relativeSyncTime(null,10000),'ตรวจหัวใจล่าสุด');assert.equal(relativeSyncTime(10000,18000),'อัปเดตเมื่อสักครู่');assert.equal(relativeSyncTime(10000,22000),'อัปเดต 12 วินาทีที่แล้ว');assert.equal(relativeSyncTime(10000,130000),'อัปเดต 2 นาทีที่แล้ว');});

test('a concurrent approval already present in a live snapshot is not lost before its event arrives',async()=>{const h=harness();h.setData([{...donation('a'),createdAt:'2026-09-09T10:00:00Z'}]);await h.sync.refresh('initial');h.setData([{...donation('a'),createdAt:'2026-09-09T10:00:00Z'},{...donation('b'),createdAt:'2026-09-09T10:00:01Z'},{...donation('c'),createdAt:'2026-09-09T10:00:02Z'}]);await h.sync.live('b');assert.deepEqual(h.updates.at(-1).meta.liveDonations.map(d=>d.id),['b','c']);const n=h.calls();await h.sync.live('c');assert.equal(h.calls(),n);});
