import test from 'node:test';import assert from 'node:assert/strict';import {PGlite} from '@electric-sql/pglite';import {readFile} from 'node:fs/promises';import {randomUUID} from 'node:crypto';
test('global clicks sum atomically, retry once, cap each animal and restrict writes',async t=>{
const db=new PGlite();t.after(()=>db.close());await db.exec('create role anon;create role authenticated;create schema heart_private;');await db.exec(await readFile('supabase/migrations/202609090004_global_hatching.sql','utf8'));
const call=async(id=null,seq=0,rose=0,praew=0)=>(await db.query('select public.heart_hatch($1,$2,$3,$4) as result',[id,seq,rose,praew])).rows[0].result;
const a=randomUUID(),b=randomUUID();assert.deepEqual(await call(),{rose:0,praew:0});await Promise.all([call(a,1,30,0),call(b,1,20,0)]);assert.deepEqual(await call(),{rose:50,praew:0});assert.deepEqual(await call(a,1,30,0),{rose:50,praew:0});await assert.rejects(call(a,1,31,0));await assert.rejects(call(a,2,10,0));await assert.rejects(call(randomUUID(),1,101,0));await assert.rejects(call(randomUUID(),1,-1,5));await assert.rejects(call(randomUUID(),2,1,0));
await db.exec("update heart_private.hatch_clients set updated_at=now()-interval '3 seconds';update public.heart_hatching set updated_at=now()-interval '3 seconds'");await call(a,2,0,25);assert.deepEqual((await db.query('select rose,praew from public.heart_hatching')).rows[0],{rose:50,praew:25});await call(b,2,1,0);assert.deepEqual((await db.query('select rose,praew from public.heart_hatching')).rows[0],{rose:50,praew:25});assert.deepEqual(await call(),{rose:51,praew:25});
await db.exec('update heart_private.hatch_total set rose=99999,praew=99990');assert.deepEqual(await call(randomUUID(),1,20,0),{rose:100000,praew:99990});assert.deepEqual(await call(randomUUID(),1,0,20),{rose:100000,praew:100000});
await db.exec('set role anon');assert.deepEqual(await call(),{rose:100000,praew:100000});await assert.rejects(db.exec('update public.heart_hatching set rose=0'));await assert.rejects(db.exec('select * from heart_private.hatch_clients'));await assert.rejects(db.exec('update heart_private.hatch_total set rose=0'));await db.exec('reset role');
});
