import test from 'node:test';import assert from 'node:assert/strict';import {PGlite} from '@electric-sql/pglite';import {readFile} from 'node:fs/promises';import {randomUUID} from 'node:crypto';
import {publicMemory,representativeHearts,createArrivalSession} from '../src/services/heartMemories.js';
import {getRoomStage,crossedRoomStages,getRoomProgress,roomSpecials} from '../src/data/roomEvolution.js';
const gift={id:'test',status:'approved',recipient:'rose',heartType:'ruby',quantity:5,supporterName:'Mint',createdAt:'2026-09-09T12:00:00Z',message:'ไทย 💖 <script>safe text</script>'};
test('memories exclude pending/rejected, strip secrets and mask anonymous identity',()=>{assert.equal(publicMemory({...gift,status:'pending'}),null);assert.equal(publicMemory({...gift,status:'rejected'}),null);const d=publicMemory({...gift,anonymous:true,socialUsername:'SECRET',adminNote:'SECRET',slipPath:'SECRET'});assert.equal(d.supporterName,'A Mysterious Supporter');assert.equal(d.socialUsername,'');assert.ok(!JSON.stringify(d).includes('SECRET'));assert.equal(d.message,gift.message);assert.equal(d.quantity,5);});
test('virtual hearts have stable IDs, share one memory and stay bounded',()=>{const hearts=representativeHearts([gift],'rose');assert.equal(hearts.length,5);assert.equal(hearts[0].id,'test-heart-1');assert.equal(hearts[4].memory.id,'test');assert.equal(representativeHearts([{...gift,quantity:100000}],'rose').length,10);assert.equal(representativeHearts([gift],'praew').length,0);});
test('rooms independently cross existing thresholds and accumulate objects',()=>{assert.equal(getRoomStage('rose',497).minHearts,0);assert.equal(crossedRoomStages('rose',497,502).length,1);assert.equal(crossedRoomStages('rose',497,499).length,0);assert.equal(crossedRoomStages('praew',0,5001).length,5);assert.equal(getRoomStage('praew',500).unlocks.length,1);assert.equal(getRoomStage('rose',5000).unlocks.length,5);assert.equal(getRoomProgress('rose',502).remaining,498);assert.equal(getRoomProgress('rose',5000).next,null);assert.equal(roomSpecials(2000).length,3);});
test('arrival receipt survives remount and storage denial cannot break playback',()=>{const values=new Map(),storage={getItem:k=>values.get(k),setItem:(k,v)=>values.set(k,v)};const a=createArrivalSession(storage);assert.equal(a.claim(gift),true);assert.equal(a.claim(gift),false);assert.equal(createArrivalSession(storage).claim(gift),false);const broken=createArrivalSession({getItem(){throw Error();},setItem(){throw Error();}});assert.equal(broken.claim(gift),true);assert.equal(broken.claim(gift),false);});
test('public SQL memories paginate, protect privacy, count exactly and remove revoked approvals',async t=>{
 const db=new PGlite();t.after(()=>db.close());await db.exec('create role anon;create role authenticated;create schema heart_private;create table heart_private.orders(id uuid primary key,data jsonb);create table heart_private.donations(id uuid primary key,data jsonb);');
 for(const file of ['202609100005_collection_realtime.sql','202609100006_heart_memories.sql'])await db.exec(await readFile('supabase/migrations/'+file,'utf8'));
 const all=[];for(let i=0;i<60;i++){const d={...gift,id:randomUUID(),quantity:i+1,recipient:i===59?'praew':'rose',anonymous:i===0,socialUsername:i===0?'SECRET':'@mint',supporterName:i===0?'SECRET':'Mint',slipPath:'SECRET',createdAt:new Date(Date.UTC(2026,8,9,12,i)).toISOString()};all.push(d);await db.query('insert into heart_private.orders values($1,$2)',[d.id,{status:i===1?'pending':'approved'}]);await db.query('insert into heart_private.donations values($1,$2)',[d.id,d]);}
 const rpc=async(name,args=[]) => (await db.query('select public.'+name+'('+args.map((_,i)=>'$'+(i+1)).join(',')+') as data',args)).rows[0].data;
 await db.exec('set role anon');await assert.rejects(db.query('select * from heart_private.approved_memories'));
 const first=await rpc('heart_memories');assert.equal(first.length,24);assert.ok(!JSON.stringify(first).includes('SECRET'));const last=first.at(-1);const page=await rpc('heart_memories',[null,null,'',false,{stamp:last.createdAt,id:last.id},null]);assert.equal(page.length,24);assert.ok(!page.some(d=>first.some(x=>x.id===d.id)));
 const hidden=await rpc('heart_memories',[null,null,'SECRET']);assert.equal(hidden.length,0);const anon=await rpc('heart_memories',[null,null,'',false,null,[all[0].id]]);assert.equal(anon[0].supporterName,'A Mysterious Supporter');assert.equal(anon[0].socialUsername,'');
 const pending=await rpc('heart_memories',[null,null,'',false,null,[all[1].id]]);assert.equal(pending.length,0);
 const world=await rpc('heart_world');assert.equal(world.groups.reduce((n,g)=>n+g.quantity,0),1828);assert.equal(world.donations.length,25);assert.equal(world.donations.filter(d=>d.recipient==='praew').length,1);
 await db.exec('reset role');await db.query('update heart_private.orders set data=$2 where id=$1',[all[59].id,{status:'rejected'}]);await db.exec('set role anon');assert.equal((await rpc('heart_world')).groups.some(g=>g.recipient==='praew'),false);await db.exec('reset role');await db.query('delete from heart_private.donations where id=$1',[all[0].id]);assert.equal((await rpc('heart_memories',[null,null,'',false,null,[all[0].id]])).length,0);
});
