import test from 'node:test';import assert from 'node:assert/strict';import {PGlite} from '@electric-sql/pglite';import {readFile} from 'node:fs/promises';import {randomUUID} from 'node:crypto';
const migration=()=>readFile('supabase/migrations/202609240012_pet_bath_carryover.sql','utf8');
async function setup(){const db=new PGlite();await db.exec('create role anon;create role authenticated;create schema heart_private;');for(const f of ['202609090004_global_hatching.sql','202609220010_pet_bath.sql','202609220011_pet_bath_rewards.sql'])await db.exec(await readFile('supabase/migrations/'+f,'utf8'));await db.exec('update heart_private.hatch_total set rose=100000,praew=100000');return db;}
const read=async db=>(await db.query('select public.heart_pet_bath() as s')).rows[0].s;
const help=async(db,round,stage)=> (await db.query("select public.heart_pet_bath('rose','help',$1,$2,$3) as s",[round,stage,randomUUID()])).rows[0].s;
async function snapshot(db,round,progress,completedAt=null){await db.query("insert into heart_private.pet_bath_requests values($1,'praew','help',99,0,$2,clock_timestamp())",[randomUUID(),{rose:{round,progress,completedAt}}]);}
test('unfinished progress and round survive read and help on later Bangkok days',async()=>{const db=await setup();try{await db.exec(await migration());await db.exec("update heart_private.pet_bath_rooms set day=current_date-4,progress=172 where recipient='rose'");let s=await read(db);assert.equal(s.rose.progress,172);assert.equal(s.rose.round,1);await db.exec("update heart_private.pet_bath_rooms set day=current_date-4 where recipient='rose'");s=await help(db,1,0);assert.equal(s.rose.progress,173);assert.equal(s.rose.round,1);}finally{await db.close();}});
test('completion awards today and only completed prior-day rounds restart',async()=>{const db=await setup();try{await db.exec(await migration());await db.exec("update heart_private.pet_bath_rooms set day=current_date-4,progress=499999 where recipient='rose'");let s=await help(db,1,3);assert.equal(s.rose.rewardPoints,20);assert.equal(s.rose.progress,500000);const row=(await db.query("select day=((clock_timestamp() at time zone 'Asia/Bangkok')::date) as today from heart_private.pet_bath_reward_ledger")).rows[0];assert.equal(row.today,true);assert.equal((await read(db)).rose.round,1);await db.exec("update heart_private.pet_bath_rooms set completed_at=clock_timestamp()-interval '2 days' where recipient='rose'");s=await read(db);assert.equal(s.rose.progress,0);assert.equal(s.rose.round,2);assert.equal(s.rose.rewardPoints,20);}finally{await db.close();}});
test('recovery uses per-snapshot round maxima, excludes completed rounds and is one-time',async()=>{const db=await setup();try{await snapshot(db,1,120,'2026-01-01T00:00:00Z');await snapshot(db,2,30);await snapshot(db,2,172);await snapshot(db,3,20);await db.exec("update heart_private.pet_bath_rooms set round=4,progress=7 where recipient='rose'");await db.exec(await migration());assert.equal((await read(db)).rose.progress,199);await db.exec(await migration());assert.equal((await read(db)).rose.progress,199);assert.equal((await db.query('select count(*)::int as n from heart_private.pet_bath_carryover_audit')).rows[0].n,2);}finally{await db.close();}});
test('recovered threshold awards once and preserves audit evidence',async()=>{const db=await setup();try{await snapshot(db,1,300000);await snapshot(db,2,200000);await db.exec("update heart_private.pet_bath_rooms set round=2,progress=200000 where recipient='rose'");await db.exec(await migration());let s=await read(db);assert.equal(s.rose.progress,500000);assert.equal(s.rose.rewardPoints,20);await db.exec(await migration());s=await read(db);assert.equal(s.rose.rewardPoints,20);await db.exec('set role anon');await assert.rejects(db.exec('select * from heart_private.pet_bath_carryover_audit'));}finally{await db.close();}});
