import test from 'node:test';
import assert from 'node:assert/strict';
import {mockDonations} from '../src/data/mockDonations.js';
import {resolveHearts} from '../src/data/heartTypes.js';
import {getCollectionStats,createDonation,getDonations,searchSupporters,subscribeToDonations,STORAGE_KEY} from '../src/services/donationService.js';
import {getNewDiscoveries,getUnlockedCollectibles,getUnlockedHearts} from '../src/services/progressionService.js';
import {simulatePayment} from '../src/services/paymentService.js';
const storage=new Map();globalThis.localStorage={getItem:key=>storage.get(key)??null,setItem:(key,value)=>storage.set(key,value)};
const input={recipient:'rose',heartType:'pink',quantity:31,supporterName:'Test Supporter',message:'With love',anonymous:false,socialUsername:'@test'};

test('seed totals and each heart type agree',()=>{const s=getCollectionStats(mockDonations);assert.equal(s.total,469);assert.equal(s.rose.total,235);assert.equal(s.praew.total,234);assert.deepEqual(s.rose.types,{pink:128,ruby:64,amber:31,golden:12});assert.deepEqual(s.praew.types,{pink:119,ruby:72,amber:26,golden:17});});
test('fixed and amount modes calculate exact prices',()=>{assert.equal(resolveHearts({heartType:'golden',quantity:3})[0].amount,600);assert.deepEqual(resolveHearts({mode:'amount',amount:270}),[{heartType:'golden',quantity:1,amount:200},{heartType:'ruby',quantity:1,amount:50},{heartType:'pink',quantity:1,amount:20}]);assert.throws(()=>resolveHearts({mode:'amount',amount:21}));for(const quantity of [0,-1,1.2,101,NaN])assert.throws(()=>resolveHearts({heartType:'pink',quantity}));});
test('milestone crossing is exact and catches multiple discoveries',()=>{assert.equal(getNewDiscoveries(469,499).length,0);assert.equal(getNewDiscoveries(469,500)[0].id,'moon');assert.equal(getNewDiscoveries(500,501).length,0);assert.equal(getNewDiscoveries(469,2001).length,3);assert.equal(getUnlockedHearts(469).length,0);assert.equal(getUnlockedHearts(500).length,1);assert.equal(getUnlockedCollectibles('rose',249).length,1);assert.equal(getUnlockedCollectibles('rose',250).length,2);});
test('create persists donation, computes price, and emits one event',()=>{storage.clear();let events=0;const unsub=subscribeToDonations(()=>events++);const d=createDonation({...input,amount:1});unsub();assert.equal(d.amount,620);assert.equal(getDonations().length,mockDonations.length+1);assert.equal(getCollectionStats(getDonations()).total,500);assert.equal(events,1);assert.equal(JSON.parse(storage.get(STORAGE_KEY))[0].id,d.id);});
test('search matches name, social, ID and returns full history without anonymous disclosure',()=>{storage.clear();const d=createDonation(input);assert.equal(searchSupporters('@test')[0].total,31);assert.equal(searchSupporters(d.id)[0].name,'Test Supporter');assert.equal(searchSupporters('test supporter')[0].rose.total,31);createDonation({...input,anonymous:true,supporterName:'Hidden',socialUsername:'@secret'});assert.equal(searchSupporters('@secret').length,0);assert.equal(searchSupporters('Hidden').length,0);});
test('invalid data and unavailable storage do not emit successful donations',()=>{storage.clear();assert.throws(()=>createDonation({...input,supporterName:' '}));assert.throws(()=>createDonation({...input,message:'x'.repeat(121)}));assert.throws(()=>createDonation({...input,recipient:'other'}));storage.set(STORAGE_KEY,'invalid-json');assert.throws(()=>getDonations());storage.clear();});
test('payment explicitly returns simulated success and supports failure',async()=>{assert.equal((await simulatePayment()).status,'simulated');await assert.rejects(simulatePayment({fail:true}),/interrupted/);});
