import {useState,useRef} from 'react';
import {Check,ChevronLeft,Minus,Plus,Moon,Sun} from 'lucide-react';
import Modal from './Modal';
import {Heart} from './Artwork';
import {heartTypes} from '../data/heartTypes';
import {createDonation} from '../services/donationService';
import {simulatePayment} from '../services/paymentService';
const steps=['Recipient','Heart','Your note','Review','Demo payment'];
export default function DonationModal({initialRecipient,onClose}){
 const [step,setStep]=useState(0),[form,setForm]=useState({recipient:initialRecipient||'rose',heartType:'pink',quantity:1,supporterName:'',anonymous:false,message:'',socialUsername:''}),[busy,setBusy]=useState(false),[error,setError]=useState('');const lock=useRef(false);
 const set=(key,value)=>setForm(p=>({...p,[key]:value}));const heart=heartTypes.find(h=>h.id===form.heartType);
 async function pay(){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await simulatePayment();createDonation(form);onClose();}catch{setError('Something interrupted the spell. Please try again.');lock.current=false;setBusy(false);}}
 return <Modal title={['Who is this heart for?','Choose a little magic.','Make it yours.','A heart, ready to send.','One last little spell.'][step]} onClose={()=>{if(!busy)onClose();}}><div className="steps" aria-label={`Step ${step+1} of 5: ${steps[step]}`}>{steps.map((s,i)=><span key={s} className={i<=step?'done':''}><i>{i<step?<Check size={12}/>:i+1}</i><small>{s}</small></span>)}</div>
 <form onSubmit={e=>{e.preventDefault();setError('');setStep(s=>s+1);}}>
 {step===0&&<><p className="muted">Every heart adds something beautiful to their room.</p><div className="recipient-options">{['rose','praew'].map(id=><button key={id} type="button" aria-pressed={form.recipient===id} className={`recipient-option ${id} ${form.recipient===id?'selected':''}`} onClick={()=>set('recipient',id)}>{id==='rose'?<Moon size={36}/>:<Sun size={36}/>}<b>Send to {id==='rose'?'Rose':'Praew'}</b><small>{id==='rose'?'Moonlight & roses':'Sunshine & wishes'}</small>{form.recipient===id&&<Check size={17}/>}</button>)}</div></>}
 {step===1&&<><div className="heart-options">{heartTypes.map(h=><button type="button" key={h.id} className={form.heartType===h.id?'selected':''} aria-pressed={form.heartType===h.id} onClick={()=>set('heartType',h.id)}><Heart color={h.color}/><b>{h.name}</b><small>{h.meaning}</small><span>{h.price} THB</span></button>)}</div><div className="quantity"><label htmlFor="quantity">How many hearts?</label><div><button type="button" aria-label="Remove one heart" disabled={form.quantity<=1} onClick={()=>set('quantity',form.quantity-1)}><Minus size={16}/></button><input id="quantity" type="number" min="1" max="100" required value={form.quantity} onChange={e=>set('quantity',e.target.value===''?'':Number(e.target.value))}/><button type="button" aria-label="Add one heart" disabled={form.quantity>=100} onClick={()=>set('quantity',Number(form.quantity)+1)}><Plus size={16}/></button></div></div><p className="total-line">Total donation <b>{heart.price*form.quantity} THB</b></p></>}
 {step===2&&<div className="supporter-form"><label>Your Name<input autoComplete="name" maxLength={30} required={!form.anonymous} disabled={form.anonymous} value={form.supporterName} onChange={e=>set('supporterName',e.target.value)} placeholder="What should we call you?" pattern=".*\S.*"/></label><label className="checkbox"><input type="checkbox" checked={form.anonymous} onChange={e=>set('anonymous',e.target.checked)}/>Send anonymously</label><label>Message <span>optional</span><textarea maxLength={120} value={form.message} onChange={e=>set('message',e.target.value)} placeholder="Always cheering for you ♡"/><small>{form.message.length} / 120</small></label><label>Social username <span>optional</span><input maxLength={40} disabled={form.anonymous} value={form.socialUsername} onChange={e=>set('socialUsername',e.target.value)} placeholder="@yourname"/></label></div>}
 {step===3&&<><div className="review-heart"><Heart color={heart.color}/><p>{heart.name} × {form.quantity}</p><small>for {form.recipient==='rose'?'Rose':'Praew'}</small></div><dl className="review"><div><dt>From</dt><dd>{form.anonymous?'Anonymous':form.supporterName}</dd></div><div><dt>Message</dt><dd>{form.message||'A little heart, with love.'}</dd></div><div><dt>Total donation</dt><dd>{heart.price*form.quantity} THB</dd></div></dl></>}
 {step===4&&<div className="payment"><Heart color={heart.color}/><b>Demo payment</b><p>No money will be charged. Your simulated heart will join the collection on this device.</p><strong>{heart.price*form.quantity} THB</strong></div>}
 {error&&<p role="alert" className="error">{error}</p>}
 <div className="flow-actions">{step>0&&<button type="button" className="text-button" disabled={busy} onClick={()=>setStep(s=>s-1)}><ChevronLeft size={16}/>Back</button>}{step<4?<button className="primary" type="submit">Continue <span>→</span></button>:<button className="primary" type="button" disabled={busy} onClick={pay}>{busy?'Sending your heart…':'Simulate Successful Donation'}</button>}</div>
 </form></Modal>
}
