import {useEffect,useRef,useState} from 'react';
import {HATCH_TARGET} from '../services/hatching';
import {FamiliarArt} from './Familiar';
export default function HatchingGame({count,onTap,recipient='rose',completed,disabled=false}){
 const name=recipient==='rose'?'กระต่ายของโรส':'อัลปาก้าของแพรว';
 const button=useRef(null),[celebrate,setCelebrate]=useState(false);const hatched=completed??count>=HATCH_TARGET;
 useEffect(()=>{if(hatched)setCelebrate(true);},[hatched]);
 const stage=Math.min(3,Math.floor(count/HATCH_TARGET*4));
 function tap(){if(hatched||disabled)return;onTap();if(!matchMedia('(prefers-reduced-motion: reduce)').matches){button.current?.getAnimations().forEach(a=>a.cancel());button.current?.animate([{transform:'scale(1) rotate(0deg)'},{transform:'scale(.91) rotate(-5deg)'},{transform:'scale(1.06) rotate(4deg)'},{transform:'scale(1) rotate(0deg)'}],{duration:180});}}
 if(hatched)return <section className="hatch-game hatch-complete" aria-label="สัตว์ที่ฟักแล้ว"><span aria-hidden="true">✦</span><p role="status">{name}ฟักแล้ว! ทุกคนช่วยกันทำภารกิจสำเร็จแล้ว</p>{celebrate&&<div className="hatch-friends"><span className="hatch-shell shell-left" aria-hidden="true">◒</span><span className="hatch-shell shell-right" aria-hidden="true">◓</span><FamiliarArt kind={recipient==='rose'?'rabbit':'alpaca'} awake/><button onClick={()=>setCelebrate(false)}>เย้! ฟักสำเร็จแล้ว ♡</button></div>}</section>;
 return <section className="hatch-game" aria-labelledby={'hatch-title-'+recipient}><div><span className="eyebrow">TAP A LITTLE MAGIC</span><h2 id={'hatch-title-'+recipient}>ไข่{name}</h2><p>กดไข่ให้ครบ {HATCH_TARGET.toLocaleString()} ครั้ง เพื่อพบ{name}</p></div><button ref={button} disabled={disabled} type="button" className={'hatch-egg crack-'+stage} onClick={tap} aria-label={'กดไข่เพื่อฟัก'+name}><svg viewBox="0 0 180 200" aria-hidden="true"><ellipse cx="90" cy="185" rx="58" ry="9" fill="#bb90a5" opacity=".15"/><path d="M90 12C56 12 23 82 23 124c0 39 28 59 67 59s67-20 67-59C157 82 124 12 90 12Z" fill="#fff1df" stroke="#b992ad" strokeWidth="3"/><path d="M65 35Q43 63 39 92" fill="none" stroke="white" strokeWidth="9" strokeLinecap="round"/><g fill="#e6bad0"><ellipse cx="60" cy="119" rx="12" ry="9"/><ellipse cx="126" cy="102" rx="10" ry="15"/><ellipse cx="103" cy="47" rx="8" ry="11"/><ellipse cx="95" cy="157" rx="15" ry="8"/></g><g fill="none" stroke="#9b758e" strokeWidth="3" strokeLinejoin="round">{stage>=1&&<path d="m91 62-8 22 13 10-11 20"/>}{stage>=2&&<path d="m85 114 21 12-10 17 9 28M96 94l22-7 13 11 18-7"/>}{stage>=3&&<path d="m85 114-22 5-14-15-24 13M91 62l16-15-5-26"/>}</g></svg><span className="hatch-tap">TAP! ♡</span></button><div className="hatch-meter"><strong>{count.toLocaleString()} / {HATCH_TARGET.toLocaleString()}</strong><progress value={count} max={HATCH_TARGET} aria-label="จำนวนครั้งที่กดไข่"/><span>{stage===0?'แตะไข่เพื่อเริ่มฟัก':stage===1?'ไข่เริ่มร้าวแล้ว!':stage===2?'ได้ยินเสียงข้างในไหม?':'อีกนิดเดียว… เพื่อนใหม่กำลังมา!'}</span></div><small>แตะไข่เพื่อสะสมยอด · เล่นฟรี</small></section>;
}
