import {ShareCard} from './Collections';
import {specialHearts} from '../data/specialHearts';
import {useEffect,useState} from 'react';
import Modal from './Modal';
import {Heart} from './Artwork';
import {heartTypes} from '../data/heartTypes';
import {fetchMemories} from '../services/donationService';
import {publicMemory} from '../services/heartMemories';
import {useCollection} from '../hooks/useCollection';
export function MemoryDetail({donation,onClose}){
 const [memory,setMemory]=useState(()=>publicMemory(donation)),[error,setError]=useState(''),[sharing,setSharing]=useState(false);const {lastSyncedAt}=useCollection();
 useEffect(()=>{let alive=true;fetchMemories({ids:[donation.id]}).then(rows=>{if(alive){setMemory(rows[0]||null);setError('');}}).catch(()=>{if(alive)setError('ยังตรวจข้อมูลล่าสุดไม่ได้ กรุณาลองเปิดอีกครั้ง');});return()=>{alive=false;};},[donation.id,lastSyncedAt]);
 const h=heartTypes.find(h=>h.id===memory?.heartType);
 if(sharing&&memory)return <ShareCard donation={memory} onClose={()=>setSharing(false)} backLabel="Heart Memory"/>;
 return <Modal title="Heart Memory" onClose={onClose}>{memory?<article className={'heart-memory-card memory-'+h.id} style={{'--memory-color':h.color}}><span className="memory-stars" aria-hidden="true">✧　✦　✧</span><Heart color={h.color}/><h3>{h.name}</h3><p>{h.meaning}</p><span className="eyebrow">For {memory.recipient==='rose'?'Rose':'Praew'}</span><h4>From {memory.supporterName}</h4><blockquote>{memory.message||'A little heart, with love.'}</blockquote><p>{memory.quantity.toLocaleString()} hearts{Number.isFinite(memory.amount)?' · '+memory.amount.toLocaleString()+' THB':''}</p><time dateTime={memory.createdAt}>{new Date(memory.createdAt).toLocaleString('th-TH')}</time>{specialHearts.filter(h=>memory.memoryMilestones.includes(h.unlock)).map(h=><p key={h.id} className="memory-milestone" style={{color:h.color}}>✦ Helped discover {h.name}</p>)}<small>Heart Memory #{memory.id}</small><button className="secondary" onClick={()=>setSharing(true)}>Share / Download this memory</button></article>:<p className="empty">ความทรงจำนี้ไม่พร้อมแสดงแล้ว</p>}{error&&<p role="status">{error}</p>}</Modal>;
}
export function MemoryExplorer({initialSearch='',ids=null}){
 const {lastSyncedAt}=useCollection();const [recipient,setRecipient]=useState(''),[type,setType]=useState(''),[search,setSearch]=useState(initialSearch),[oldest,setOldest]=useState(false),[rows,setRows]=useState([]),[selected,setSelected]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[cursor,setCursor]=useState(null),[more,setMore]=useState(false),[pages,setPages]=useState([]),[retry,setRetry]=useState(0);
 const key=JSON.stringify({recipient,type,search,oldest,ids});
 useEffect(()=>{setCursor(null);setPages([]);setRows([]);},[key,lastSyncedAt]);
 useEffect(()=>{let alive=true;setLoading(true);const timer=setTimeout(()=>{fetchMemories({recipient:recipient||null,type:type||null,search,oldest,cursor,ids}).then(data=>{if(!alive)return;setRows(data);setMore(data.length===24);setError('');}).catch(()=>{if(alive)setError('ยังโหลดความทรงจำไม่ได้ กรุณาลองอีกครั้ง');}).finally(()=>{if(alive)setLoading(false);});},250);return()=>{alive=false;clearTimeout(timer);};},[key,cursor,lastSyncedAt,retry]);
 return <section className="memory-explorer"><div className="memory-filters"><label>Collection<select value={recipient} onChange={e=>setRecipient(e.target.value)}><option value="">All</option><option value="rose">Rose</option><option value="praew">Praew</option></select></label><label>Heart<select value={type} onChange={e=>setType(e.target.value)}><option value="">All hearts</option>{heartTypes.map(h=><option value={h.id} key={h.id}>{h.name}</option>)}</select></label><label>Order<select value={String(oldest)} onChange={e=>setOldest(e.target.value==='true')}><option value="false">Newest</option><option value="true">Oldest</option></select></label><label className="memory-search">Find a supporter<input value={search} maxLength={100} onChange={e=>setSearch(e.target.value)} placeholder="ชื่อผู้สนับสนุน หรือ Donation ID"/></label></div><div className="memory-grid">{rows.map(d=>{const h=heartTypes.find(h=>h.id===d.heartType);return <button className="memory-tile" key={d.id} onClick={()=>setSelected(d)} style={{'--memory-color':h.color}}><Heart color={h.color}/><b>{h.name} × {d.quantity.toLocaleString()}</b><span>For {d.recipient==='rose'?'Rose':'Praew'} · {d.supporterName}</span><p>{d.message||'A little heart, with love.'}</p><time>{new Date(d.createdAt).toLocaleDateString('th-TH')}</time></button>;})}</div>{loading&&<p role="status">กำลังเปิดหน้าความทรงจำ…</p>}{error&&<p role="status">{error} <button onClick={()=>setRetry(n=>n+1)}>ลองอีกครั้ง</button></p>}{!loading&&!error&&!rows.length&&<p className="empty">ยังไม่มีความทรงจำที่ตรงกัน ♡</p>}{!!pages.length&&!loading&&<button className="secondary full" onClick={()=>{setCursor(pages.at(-1));setPages(p=>p.slice(0,-1));}}>← หน้าก่อน</button>}{more&&!loading&&!error&&<button className="secondary full" onClick={()=>{setPages(p=>[...p,cursor]);const d=rows.at(-1);setCursor({stamp:d.createdAt,id:d.id});}}>เปิดหน้าถัดไป</button>}{selected&&<MemoryDetail donation={selected} onClose={()=>setSelected(null)}/>}</section>;
}
