import {getRoomProgress,roomSpecials} from '../data/roomEvolution';
import {Prop} from './Artwork';
function Garden({recipient}){const rose=recipient==='rose';return <svg viewBox="0 0 360 110" aria-hidden="true"><g stroke={rose?'#a3a484':'#a8ab80'} strokeWidth="2" fill="none">{[16,39,321,344].map((x,i)=><path key={x} d={'M'+x+' 106 Q'+(x+12)+' 76 '+x+' '+(35+i%2*20)+' M'+x+' 83 q-19-14-12-21 M'+x+' 74 q19-13 13-19'}/>)}</g>{[16,39,321,344].map((x,i)=><g key={x} transform={'translate('+x+' '+(35+i%2*20)+')'} fill={rose?'#d296b0':'#dfbf83'}>{Array.from({length:5},(_,p)=><ellipse key={p} rx="6" ry="10" cy="-7" transform={'rotate('+p*72+')'}/>)}<circle r="4" fill="#fff0cd"/></g>)}</svg>;}
export function RoomEnvironment({recipient,total,sharedTotal,evolution}){
 const {stage}=getRoomProgress(recipient,total);return <div className={'room-environment '+(evolution?.recipient===recipient?'evolving':'')} aria-label={stage.name}>
 {stage.unlocks.map((item,index)=><div key={item} className={'environment-'+item} style={{'--reveal-delay':index*.12+'s'}} aria-label={item}>{item==='garden'?<Garden recipient={recipient}/>:item==='window'?<span>{recipient==='rose'?'☾':'☀'}　✧</span>:item==='alcove'?<Prop kind={recipient==='rose'?'mirror':'crystal'}/>:item==='library'?<Prop kind="book"/>:<span>✧　♡　✧</span>}</div>)}
 <div className="room-specials">{roomSpecials(sharedTotal).map(h=><span key={h.id} title={h.name} style={{color:h.color}}>{({moon:'☾',crystal:'◇',angel:'❧',eternal:'♡'})[h.id]}</span>)}</div></div>;
}
export function RoomEvolutionProgress({recipient,total,evolution}){const {stage,next,value,max,remaining}=getRoomProgress(recipient,total);return <div className="room-evolution-progress"><span className="eyebrow">ROOM MAGIC · {stage.name}</span><div role="progressbar" aria-label="Room evolution" aria-valuemin={0} aria-valuemax={max} aria-valuenow={Math.min(max,value)}><i style={{width:Math.min(100,value/max*100)+'%'}}/></div><small>{next?remaining.toLocaleString()+' hearts until '+next.name:'A sanctuary filled with your memories'}</small>{evolution?.recipient===recipient&&<p className="evolution-notice" role="status">✦ Room evolved · {evolution.stages.map(s=>s.name).join(' · ')}</p>}</div>;}
