import {useState} from 'react';
import Familiar from './Familiar';
import {Moon,Sun,Sparkles,ArrowUpRight,LockKeyhole} from 'lucide-react';
import {Heart,Prop,Candle} from './Artwork';
import {heartTypes} from '../data/heartTypes';
import {collectibleItems} from '../data/collectibleItems';
import {milestones} from '../data/milestones';
import {useCollection} from '../hooks/useCollection';
export function Progress({value,max,label}){return <div className="progress" role="progressbar" aria-label={label} aria-valuemin={0} aria-valuemax={max} aria-valuenow={Math.min(value,max)}><span style={{width:`${Math.min(100,value/max*100)}%`}}/></div>}
export function Room({character,onCollect,onCabinet,active,onStory}){
 const {stats,arrival,notice,donations}=useCollection();const {id,name}=character,s=stats[id]; const [previewId,setPreviewId]=useState(null);const preview=collectibleItems[id].find(i=>i.id===previewId);const previewLocked=preview && preview.at>s.total;
 const next=collectibleItems[id].find(i=>i.at>s.total);const unlocked=collectibleItems[id].filter(i=>i.at<=s.total);
 const latest=donations.filter(d=>d.recipient===id&&!d.id.startsWith('demo-')).at(-1); const count=Math.min(96,Math.ceil(s.total/5));
 const colors=heartTypes.flatMap(h=>Array(Math.max(0,Math.round(s.types[h.id]/Math.max(1,s.total)*100))).fill(h.color));
 return <section className={`room ${id} ${active?'mobile-active':''} ${arrival?.recipient===id?'receiving':''}`} aria-label={`${name}'s collection`}>
  <div className="room-heading"><div className="sigil">{id==='rose'?<Moon size={18}/>:<Sun size={20}/>}</div><h2>{name}<span>’s collection</span></h2><p>{character.subtitle}</p></div>
  <div className="room-stage" data-jar={id}>
   <div className="arch"><span className="arch-star s1">✧</span><span className="arch-star s2">✦</span><span className="arch-star s3">✧</span><div className="celestial">{id==='rose'?<Moon/>:<Sun/>}</div></div>
   <div className="hanging left">✧</div><div className="hanging right">✧</div>
   {character.artwork&&<img className="licensed-art" src={character.artwork} alt={`${name} artwork`}/>}
   <div className="jar-wrap"><svg className="jar-glass" viewBox="0 0 300 340" aria-hidden="true"><defs><linearGradient id={`glass-${id}`} x2="1" y2=".7"><stop stopColor="#fff5ef" stopOpacity=".8"/><stop offset=".45" stopColor={id==='rose'?'#eac9df':'#f3d5bb'} stopOpacity=".22"/><stop offset="1" stopColor="#fff3e7" stopOpacity=".8"/></linearGradient></defs><path d="M110 62Q75 80 51 126C-14 237 71 313 150 327C229 313 314 237 249 126Q225 80 190 62Z" fill={`url(#glass-${id})`} stroke={id==='rose'?'#bd8ca9':'#c8a27a'} strokeWidth="2.5"/><path d="M97 89Q39 133 49 200M71 245q14 27 40 38" fill="none" stroke="#fff9ef" strokeWidth="8" strokeLinecap="round" opacity=".85"/><ellipse cx="150" cy="64" rx="46" ry="11" fill="#ead1c7" stroke="#b98b85" strokeWidth="2"/><rect x="105" y="44" width="90" height="20" rx="8" fill="#ecd5b6" stroke="#b89b76" strokeWidth="2"/><path d="M113 49H187M117 57H183" stroke="#c4a179"/><path d="M137 41q-13-20 13-29 26 9 13 29Z" fill="#ead7bb" stroke="#b89b85" strokeWidth="2"/></svg>
    <div className="jar-hearts">{Array.from({length:count},(_,i)=>{const row=Math.floor(i/9),col=i%9;return <Heart key={i} color={colors[(i*37)%colors.length]||heartTypes[i%4].color} style={{left:`${8+col*9+(row%2)*3}%`,bottom:`${4+row*6.5}%`,width:`${21+(i%4)*3}px`,transform:`rotate(${(i*29)%60-30}deg)`,animationDelay:`${-i*.39}s`}}/>;})}</div>
    {latest&&<button className={`story-heart ${notice?.id===latest.id?'story-heart-new':''}`} aria-label={`Read ${latest.supporterName}'s heart story for ${name}`} onClick={()=>onStory(latest)}><Heart color={heartTypes.find(h=>h.id===latest.heartType).color}/><span>{notice?.id===latest.id?'NEW STORY':'READ STORY'}</span></button>}<div className="jar-emblem">{id==='rose'?<Moon size={19}/>:<Sun size={19}/>}</div>
   </div>
   <div className="candle candle-left"><Candle/></div><div className="candle candle-right"><Candle/></div><div className="books"><i/><i/><i/></div>
   <div className="room-items">{unlocked.filter(i=>i.kind!=='familiar-charm').map(i=><div key={i.id} title={i.name} className={`room-item item-${i.kind}`}><Prop kind={i.kind} color={id==='rose'?'#cd8ba5':'#d9ad70'}/></div>)}</div>
   <Familiar recipient={id} total={s.total} celebrating={arrival?.recipient===id || notice?.recipient===id} previewCharm={previewLocked && preview.kind==='familiar-charm'}/>{previewLocked && preview.kind!=='familiar-charm' && <div className={`room-item item-${preview.kind} item-preview`} aria-label={`${preview.name} placement preview`}><Prop kind={preview.kind} color={id==='rose'?'#cd8ba5':'#d9ad70'}/><span>PREVIEW</span></div>}<div className="shelf"/><span className="shelf-label">{id==='rose'?'THE MOONLIGHT ROOM':'THE SUNLIGHT ROOM'}</span>
   {notice?.recipient===id&&<div className="supporter-message"><span>“{notice.message||'A little heart, with love.'}”</span><small>from {notice.supporterName}</small></div>}
  </div>
  <div className="room-stats"><div className="count"><strong>{s.total.toLocaleString()}</strong><span>hearts collected</span><button onClick={()=>onCollect(id)} aria-label={`Send a heart to ${name}`}><ArrowUpRight size={19}/></button></div><div className="type-counts">{heartTypes.map(h=><span key={h.id} title={`${h.name}: ${s.types[h.id]}`}><Heart color={h.color}/><b>{s.types[h.id]}</b><small>{h.name.split(' ')[0]}</small></span>)}</div><button className="next-item" aria-expanded={!!preview} onClick={()=>next?setPreviewId(preview?null:next.id):onCabinet()}><Prop kind={next?.kind||'book'}/><span><small>{next?'NEXT MAGICAL ITEM':'ROOM COMPLETE'}</small><b>{next?.name||'A room full of magic'}</b></span><span>{next?`${s.total} / ${next.at}`:'✧'}</span></button><Progress value={s.total} max={next?.at||s.total||1} label={`${name}'s next collectible`}/>{preview && <div className="item-preview-panel"><div className="preview-panel-heading"><span className="eyebrow">TRY A LITTLE MAGIC</span><button onClick={()=>setPreviewId(null)} aria-label="Close item preview">×</button></div><h3>{preview.name}</h3><p>{preview.description}</p><strong>{previewLocked?`${(preview.at-s.total).toLocaleString()} hearts to unlock`:'Already part of your room'}</strong><div className="preview-item-options" aria-label="Preview room collectibles">{collectibleItems[id].map(item=><button key={item.id} aria-label={`Preview ${item.name}`} aria-pressed={preview.id===item.id} onClick={()=>setPreviewId(item.id)}><Prop kind={item.kind}/></button>)}</div><small>Preview only. Your collection stays just as it is.</small></div>}</div>
 </section>
}
export function GrandHeart({onCollect,onCollection}){
 const {stats}=useCollection();const next=milestones.find(m=>m.at>stats.total)||milestones.at(-1);const pct=stats.total/next.at;
 return <section className={`grand stage-${Math.min(4,Math.floor(pct*4))} ${stats.total>=2000?'transformed':''}`} aria-label="Grand Heart"><div className="grand-top"><span className="eyebrow">A LITTLE MAGIC, TOGETHER</span><h1>Every heart<br/> becomes a story.</h1><p>Two collections. One magical world.<br/> Made brighter by you.</p></div><div className="grand-crystal"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><span className="orbit-star star-one">✦</span><span className="orbit-star star-two">✧</span><span className="orbit-star star-three">✦</span><Heart color="#ce92b7"/><span className="crystal-spark">✧</span><div className="crystal-base"/></div><div className="grand-progress"><h2>The Grand Heart</h2><p><strong>{stats.total.toLocaleString()}</strong><span> / {next.at.toLocaleString()} hearts</span></p><Progress value={stats.total} max={next.at} label="Community milestone"/><small>{Math.max(0,next.at-stats.total)} little hearts until {next.name}</small></div><button className="primary collect-button" onClick={()=>onCollect()}><Heart color="#f7d6df"/>Collect a Heart<Sparkles size={17}/></button><span className="demo-note">A demo of love. No real payment.</span><button className="next-discovery" onClick={onCollection}><div><Heart color={stats.total<500?'#b4a1cc':'#87bccc'}/><LockKeyhole size={13}/></div><span><small>NEXT DISCOVERY</small><b>{stats.total<500?'Moon Heart':stats.total<1000?'Crystal Heart':stats.total<2000?'Angel Heart':stats.total<5000?'Eternal Heart':'All hearts discovered'}</b></span><ArrowUpRight size={18}/></button></section>
}


