import ThemeToggle from './components/ThemeToggle';
import {MemoryDetail} from './components/HeartMemories';
import GamesPage from './components/GamesPage';
import {gameRoute} from './games/routes';
import MiniGames from './components/MiniGames';
import {adminRoute} from './services/adminRoutes';
import AdminPanel from './components/AdminPanel';
import {PersonalBook,TogetherCelebration} from './components/Memories';
import {useEffect,useRef,useState} from 'react';
import {BookOpen,Search,Music2,VolumeX,HelpCircle,ArrowUpRight,Sparkles,Heart as HeartIcon,Menu,Activity,Share2} from 'lucide-react';
import {CollectionProvider,useCollection} from './hooks/useCollection';
import {useAudio} from './hooks/useAudio';
import {characters} from './data/characters';
import {heartTypes} from './data/heartTypes';
import {Heart} from './components/Artwork';
import {GrandHeart,Room} from './components/World';
import DonationModal from './components/DonationModal';
import Modal from './components/Modal';
import {CollectionBook,SearchModal,RecentActivity,HowToPlay,Unlock,ShareCard} from './components/Collections';
function Arrival({donation}){
 const ref=useRef(null);const heart=heartTypes.find(h=>h.id===donation.heartType);
 useEffect(()=>{const target=document.querySelector(`[data-jar="${donation.recipient}"]`);if(!target){ref.current.style.opacity=0;return;}const r=target.getBoundingClientRect();if(!r.width||r.bottom<0||r.top>innerHeight){ref.current.style.opacity=0;return;}const dx=r.left+r.width/2-innerWidth/2,dy=r.top+r.height*.55-innerHeight*.48;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const animation=ref.current.animate(reduced?[{opacity:0},{opacity:1},{opacity:0}]:[{transform:'translate(-50%,-50%) scale(.3)',opacity:0},{transform:'translate(-50%,-50%) scale(1.4)',opacity:1,offset:.25},{transform:`translate(calc(-50% + ${dx*.6}px),calc(-50% + ${dy-100}px)) scale(.85)`,opacity:1,offset:.68},{transform:`translate(calc(-50% + ${dx}px),calc(-50% + ${dy}px)) scale(.3)`,opacity:0}],{duration:reduced?150:1650,easing:'cubic-bezier(.22,.7,.2,1)',fill:'forwards'});return()=>animation.cancel();},[donation]);
 return <div ref={ref} className="arrival-heart" aria-hidden="true"><span>✧</span><div className="arrival-cluster">{Array.from({length:Math.min(donation.quantity,5)},(_,i)=><Heart key={i} color={heart.color}/>)}</div><b>+{donation.quantity.toLocaleString()}</b><span>✦</span></div>
}
function Experience(){
 const [hatched,setHatched]=useState({rose:false,praew:false});

 const {stats,error,reload,arrival,notice,discoveries,dismissDiscovery,celebration,dismissCelebration}=useCollection();const [panel,setPanel]=useState(null),[recipient,setRecipient]=useState(null),[mobileRoom,setMobileRoom]=useState('rose'),[detail,setDetail]=useState(null);const audio=useAudio();
 function collect(id){setRecipient(id);setPanel('donate');}

 const close=()=>setPanel(null);
 return <div className={`app ${`${stats.total>=3000?'room-upgraded':''} ${celebration?'community-celebrating':''}`}`}><header className="topbar"><a className="brand" href="/" aria-label="Heart Collection home"><span className="brand-icon"><HeartIcon size={23}/><Sparkles size={10}/></span><span>HEART COLLECTION<small>A LITTLE LOVE, A LITTLE MAGIC</small></span></a><nav aria-label="Main navigation"><button onClick={()=>setPanel('collection')}><BookOpen size={16}/>Collection</button><button onClick={()=>setPanel('memories')}><BookOpen size={16}/>My Memories</button><button onClick={()=>setPanel('help')}><HelpCircle size={16}/>How to Play</button><button onClick={audio.toggle} disabled={audio.unavailable} aria-pressed={audio.playing}>{audio.playing?<Music2 size={16}/>:<VolumeX size={16}/>}<span>{audio.unavailable?'Music unavailable':audio.playing?'Music on':audio.preferred?'Resume music':'Music off'}</span></button><button className="search-button" onClick={()=>setPanel('search')}><Search size={17}/><span>Find your heart</span></button></nav><ThemeToggle/><span className="mobile-total">{stats.total} hearts together</span></header>
 <main>{error?<section className="archive-error"><Heart/><h1>{error}</h1><p>Your saved archive could not be loaded.</p><button className="primary" onClick={reload}>Retry</button></section>:<><div className="world-top"><span><i/>THE HEART ROOM</span><span>Collected with love, kept forever <HeartIcon size={12}/></span></div><div className="world"><div className="mobile-tabs" aria-label="Choose collection room">{characters.map(c=><button key={c.id} aria-pressed={mobileRoom===c.id} className={mobileRoom===c.id?'active':''} onClick={()=>setMobileRoom(c.id)}>{c.name}’s Collection</button>)}</div><Room hatched={hatched.rose} onStory={d=>setPanel({memory:d})} character={characters[0]} onCollect={collect} onCabinet={()=>setPanel('collection')} active={mobileRoom==='rose'}/><GrandHeart onCollect={collect} onCollection={()=>setPanel('collection')}/><Room hatched={hatched.praew} onStory={d=>setPanel({memory:d})} character={characters[1]} onCollect={collect} onCabinet={()=>setPanel('collection')} active={mobileRoom==='praew'}/></div><div className="world-caption"><span>✧</span> Let’s fill both magical collections together. <span>✧</span></div><MiniGames onHatched={setHatched}/><div className="below-world"><section className="heart-guide"><div className="section-heading"><h2>Small hearts. Beautiful meanings.</h2><span>CHOOSE YOUR MAGIC</span></div><div className="guide-hearts">{heartTypes.map(h=><button key={h.id} onClick={()=>setDetail(h)}><Heart color={h.color}/><span><b>{h.name}</b><small>{h.meaning}</small></span><span>{h.price}<small>THB</small></span></button>)}</div><p>Every heart is a little piece of your love.</p></section><RecentActivity onStory={d=>setPanel({memory:d})} onAll={()=>setPanel('activity')}/></div><footer><span>♡ Made of little moments, and lots of love.</span><button onClick={()=>setPanel('milestone-share')}><Share2 size={13}/>Share our collection</button><button onClick={()=>setPanel('memories')}><BookOpen size={13}/>My Memories</button><span className="prototype-badge">HEART COLLECTION</span></footer></>}</main>
 <div className="mobile-nav"><button onClick={()=>setPanel('collection')}><BookOpen size={19}/>Collection</button><button className="mobile-collect" onClick={()=>collect()}><HeartIcon size={20}/>Collect Heart</button><button onClick={()=>setPanel('activity')}><Activity size={19}/>Activity</button><button onClick={()=>setPanel('more')}><Menu size={19}/>More</button></div>
 {arrival&&<Arrival donation={arrival}/>}{notice&&<div className="toast" role="status"><Heart color={heartTypes.find(h=>h.id===notice.heartType).color}/><span><b>{notice.supporterName} sent {notice.recipient==='rose'?'Rose':'Praew'} a little love</b><small>{notice.quantity} heart{notice.quantity>1?'s':''} joined the collection{notice.specials?.length?' · ✦ '+notice.specials.map(h=>h.name).join(', ')+' discovered':''}</small></span><button onClick={()=>setPanel({memory:notice})}>Heart Memory <ArrowUpRight size={15}/></button></div>}
 {panel==='memories'&&<PersonalBook onClose={close}/>}{celebration&&!panel&&<TogetherCelebration hatched={hatched} event={celebration} onDone={dismissCelebration}/>} {panel==='donate'&&<DonationModal initialRecipient={recipient} onClose={close}/>}{panel==='collection'&&<CollectionBook onClose={close}/>}{panel==='search'&&<SearchModal onClose={close}/>}{panel==='help'&&<HowToPlay onClose={close}/>}{panel==='activity'&&<Modal title="Every little act of love" wide onClose={close}><RecentActivity full onStory={d=>setPanel({memory:d})}/></Modal>}{panel==='more'&&<Modal title="A little more magic" onClose={close}><div className="more-menu"><button onClick={()=>setPanel('memories')}><BookOpen/>My Memories</button><button onClick={()=>setPanel('search')}><Search/>Find your heart</button><button onClick={()=>setPanel('help')}><HelpCircle/>How to Play</button><button disabled={audio.unavailable} onClick={audio.toggle}><Music2/>{audio.unavailable?'Music unavailable':audio.playing?'Turn music off':audio.preferred?'Resume music':'Turn music on'}</button><button onClick={()=>setPanel('milestone-share')}><Share2/>Share our collection</button></div></Modal>}
 {panel?.memory&&<MemoryDetail donation={panel.memory} onClose={close}/>} {panel?.share&&<ShareCard donation={panel.share} onClose={close}/>} {panel==='milestone-share'&&<ShareCard summary={{title:'Our Grand Heart',subtitle:`${stats.total.toLocaleString()} hearts collected together`,message:'Every heart becomes part of the story.'}} onClose={close}/>}
 {detail&&<Modal title={detail.name} onClose={()=>setDetail(null)}><div className="heart-detail"><Heart color={detail.color}/><h3>{detail.meaning}</h3><p>{detail.price} THB per heart</p><div><span>Rose <b>{stats.rose.types[detail.id]} collected</b></span><span>Praew <b>{stats.praew.types[detail.id]} collected</b></span></div></div><button className="primary full" onClick={()=>{setDetail(null);collect();}}>Collect a Heart</button></Modal>}
 {!!discoveries.length&&!panel&&!celebration&&<Unlock heart={discoveries[0]} onClose={dismissDiscovery} onCollection={()=>{dismissDiscovery();setPanel('collection');}}/>}
 </div>
}
export default function App(){const path=window.location.pathname,route=adminRoute(path),game=gameRoute(path);return route?<AdminPanel {...route}/>:game?<GamesPage route={game}/>:<CollectionProvider><Experience/></CollectionProvider>}


